blog/blog/lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router
  # simply makes Phoenix router functions available in our particular router.
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BlogWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BlogWeb.Plugs.Locale, "en"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  # /s/
  scope "/", BlogWeb do
    pipe_through :browser
    # pipelines allow a set of plugs to be applied to different sets of routes.

    get "/", PageController, :index
    # get is a Phoenix macro that corresponds to the HTTP verb GET.
    #  Similar macros exist for other HTTP verbs, including POST, PUT, PATCH, DELETE, OPTIONS, CONNECT, TRACE, and HEAD.
    # The router supports other macros besides those for HTTP verbs like get, post, and put. The most important among them is resources.

    get "/hello", HelloController, :index
    get "/hello/:messenger", HelloController, :show
    # resource with all func
    resources "/users", UserController
    # resource with only two func
    resources "/posts", PostController, only: [:index, :show]
    # resource with all func except delete
    resources "/comments", CommentController, except: [:delete]
    resources "/reviews", ReviewController
    # nested resource
    resources "/client", UserController do
      resources "/order", PostController
    end
  end
  # Interestingly, we can use multiple scopes with the same path as long as we are careful not to duplicate routes.
  scope "/", AnotherAppWeb do
    pipe_through :browser

    resources "/app", AppController
  end

  scope "/admin", HelloWeb.Admin, as: :admin do
    pipe_through :browser

    resources "/review", ReviewController
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: BlogWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

blog/blog/lib/blog/application.ex
defmodule Blog.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Blog.Repo,
      # Start the Telemetry supervisor
      BlogWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Blog.PubSub},
      # Start the Endpoint (http/https)
      BlogWeb.Endpoint
      # Start a worker by calling: Blog.Worker.start_link(arg)
      # {Blog.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Blog.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    BlogWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

blog/blog/lib/blog/mailer.ex
defmodule Blog.Mailer do
  use Swoosh.Mailer, otp_app: :blog
end

blog/blog/lib/blog/repo.ex
defmodule Blog.Repo do
  use Ecto.Repo,
    otp_app: :blog,
    adapter: Ecto.Adapters.Postgres
end

blog/blog/lib/blog_web/controllers/hello_controller.ex
defmodule BlogWeb.HelloController do
  use BlogWeb, :controller
  plug HelloWeb.Plugs.Locale, "fr"
  plug HelloWeb.Plugs.Locale2, "hi" when action in [:index]
  plug HelloWeb.Plugs.Locale2, "de" when action in [:show]
  def index(conn, _params) do
    render(conn, "index.html")
  end

  def show(conn, %{"messenger" => messenger}) do
    render(conn, "show.html", messenger: messenger)
  end
end

blog/blog/lib/blog_web/controllers/page_controller.ex
defmodule BlogWeb.PageController do
  use BlogWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

blog/blog/lib/blog_web/views/error_view.ex
defmodule BlogWeb.ErrorView do
  use BlogWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

blog/blog/lib/blog_web/views/hello_view.ex
defmodule BlogWeb.HelloView do
  use BlogWeb, :view
end

blog/blog/lib/blog_web/views/layout_view.ex
defmodule BlogWeb.LayoutView do
  use BlogWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

blog/blog/lib/blog_web/views/page_view.ex
defmodule BlogWeb.PageView do
  use BlogWeb, :view
end
# import Module brings all the Functions and Macros of Module un-namespaced into your module. require Module allows you to use
# macros of Module but does not import them. (Functions of Module are always available namespaced.) use Module first requires
# module and then calls the __using__ macro on Module .

blog/blog/lib/blog_web/templates/hello/index.html.heex
<section class="phx-hero">
    <h2>Hello world,from phoenix!</h2>
    <%= link "Hello Page! using path helper", to: Routes.hello_path(@conn, :show , "Saumya") %><br>
    <p>Locale inside controller: <%= @locale %></p>
</section>
<section class="phx-hero">
    <p>Locale2 inside index function: <%= @locale2 %></p>
    <h2>How you doing?</h2>
</section>
<section class="phx-hero">
    <h2>Hiii</h2>
</section>

blog/blog/lib/blog_web/templates/hello/show.html.heex
<section class="phx-hero">
    <%# This is significant because we can use the page_path function in a template to link to the root of our application. We can then use this helper in our templates: %>

    <%= link "Welcome Page! using path helper", to: Routes.page_path(@conn, :index) %><br>
    <%= link "Hello Page! using path helper", to: Routes.hello_path(@conn, :index) %><br>
    URL = <%= Routes.hello_url(@conn, :index) %><br>
    PATH = <%= Routes.hello_path(@conn, :index) %>
        <p>Locale inside controller: <%= @locale %></p>
    <h2>Hello world,from <%= @messenger %>!</h2>
        <p>Locale2 inside show function: <%= @locale2 %></p>
</section>

blog/blog/lib/blog_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <p>Locale: <%= @locale %></p>
  <%= @inner_content %>
  <%# injects our template into the layoutbefore the HTML is sent off %>
</main>

blog/blog/lib/blog_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>


  <%= @inner_content %>
</main>

blog/blog/lib/blog_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Blog", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

blog/blog/lib/blog_web/templates/page/index.html.heex
<section class="phx-hero">

  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace of mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.6/CHANGELOG.md">v1.6 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="/hello">Blog</a>
      </li>
      <li>
        <a href="https://web.libera.chat/#elixir">#elixir on Libera Chat (IRC)</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
      <li>
        <a href="https://discord.gg/elixir">Elixir on Discord</a>
      </li>
    </ul>
  </article>
</section>